version: "3.9"

services:
  web:
    build: .
    container_name: django_dogs_ninja_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: django_dogs_ninja_db
    environment:
      POSTGRES_DB: dogs_db
      POSTGRES_USER: dogs_user
      POSTGRES_PASSWORD: dogs_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: